blacklist = [
    # 1. Reading status
    'to read', 'read in 2016', 'currently reading', 'tbr', 'read 2016', 'read 2015', 'read 2014',
    'read 2013', 'read 2012', 'read 2011', 'read 2010', 're read', 'reread', 'to reread', 'already read',
    'read again', 'read aloud', 'read alouds', 'read fiction', 'read in school', 'read as a kid',
    'read comics', 'read next', 'read 2009', 'read in english',

    # 2. Ownership/location
    'owned', 'my books', 'library', 'kindle', 'ebooks', 'books i own', 'to buy', 'owned books',
    'i own', 'my library', 'own it', 'borrowed', 'on my shelf', 'books i have', 'bookshelf',
    'home library', 'my bookshelf', 'own to read', 'own ebook', 'my ebooks', 'owned tbr',
    'ebooks i own', 'own kindle', 'owned not read', 'owned but not read', 'own on kindle',
    'kindle owned', 'own unread', 'owned unread', 'owned ebook', 'own a copy', 'my kindle books',
    'owned kindle', 'own tbr', 'kindle library', 'books owned', 'kindle to read', 'not owned',
    'do not own', 'owned not read', 'owned but not read', 'own unread', 'own a copy',

    # 3. Format or device
    'audiobook', 'ebook', 'paperback', 'hardcover', 'audiobooks', 'audio', 'e book', 'e books',
    'audio books', 'audio book', 'audible', 'library book', 'kindle books', 'nook', 'on kindle',
    'netgalley', 'overdrive', 'pdf', 'epub', 'ibooks', 'kobo', 'kindle unlimited', 'digital',
    'graphic', 'ebook owned', 'epub', 'e reader', 'calibre', 'ibooks', 'kobo', 'downloaded',
    'kindle book', 'ebooks i own',

    # 4. Rating/review-based
    '5 stars', 'favorites', 'favourites', 'favorite', 'favorite books', 'favorite series',
    'my favorites', 'favorite authors', 'favorite author', 'faves', 'favourite', 'fav',
    'gave up on', 'gave up', 'did not finish', 'dnf', 'abandoned', 'unfinished', 'didn t finish',
    'couldn t finish', 'could not finish', 'not finished', 'not read', 'never finished', 'paused',
    'stopped reading', 'not for me', 'nope', 'meh', 'dnf', 'review', 'reviewed',

    # 5. Challenge or year-based
    '2016 reading challenge', '2017 reading challenge', '2015 reading challenge', '2014 read',
    '2015 reads', '2014 reads', '2013 reads', '2012 reads', '2011 reads', '2010 reads', '2016 reads',
    '2015 books', '2014 books', '2013 books', '2012 books', '2017 reads', '2017 books',
    '2017 read', '2017 release', '2017 reading list', '2017 books read', 'books read in 2016',
    'books read in 2015', 'books read in 2014', 'books read in 2013', 'books read in 2012',
    'books read in 2017', 'books read in 2011', 'books read in 2010', 'read in 2015',
    'read in 2014', 'read in 2013', 'read in 2012', 'read in 2011', 'read in 2010', '2016 books',
    '2016 read', '2017 books read', '2017 books read', 'books read in 2016', '2016 books read',

    # 6. Meta or personal tags
    'wishlist', 'wish list', 'book club', 'bookclub', 'book club books', 'book club reads',
    'book group', 'to re read', 're read', 'reread', 'to reread', 'to read owned', 'to read own',
    'to read fiction', 'to read non fiction', 'to read nonfiction', 'to read ya', 'to read series',
    'to read classics', 'to read fantasy', 'to review', 'to purchase', 'to be read', 'to be released',
    'to read soon', 'to get', 'want to read', 'want to buy', 'want', 'need', 'need to buy',
    'need to get', 'not interested', 'maybe', 'maybe read', 'recommendations', 'next', 'next to read',
    'next in series', 'done', 'shelved', 'my shelf', 'own a copy', 'own tbr', 'top tbr', 'not for me',
    'considering', 'owned but not read', 'wishlist', 'wishlist', 'owned to read', "own have",
    "i own need to read",
    "acquired in 2016",
    "have not read",
    "to read get",
    "waiting in queue",
    "own the kindle",
    "purchased",
    "buy book",
    "swap",
    "not at library",
    "library loan",
    "book i own",
    "books won",
    "giveaways",
    "net galley",
    "librarybooks",
    "not library",
    "tryingtoget",
    "need to read",
    "to read",
    "tbr",
    "read",
    "paper back",
    "kindle own a copy",
    "kindle audio",
    "kindle ebooks",
    "print disabled",
    "physical book",
    "on kobo",
    "scanned",
    "audiobooked it",
    "e books owned",
    "play books",
    "paperback collection",
    "comixology",
    "to read kindle",
    "1999 reads",
    "2015 read",
    "read in 2017",
    "2015 challenge",
    "2006 2010",
    "to read 2015",
    "2009 books",
    "2015 reads",
    "2015 books",
    "2017 reads",
    "2017 book",
    "2017 release",
    "2017 reading list",
    "books read in 2016",
    "books read in 2015",
    "books read in 2014",
    "books read in 2013",
    "books read in 2012",
    "books read in 2011",
    "books read in 2010",
    "2016 books",
    "2016 read",
    "2017 books read",
    "2022 plan",
    "2017 listicle",
    "2016challenge",
    "2017 tbr",
    "added 2015",
    "2015 best of",
    "2015 r",
    "0 2015",
    "reading challenge 2013",
    "2016 tbr",
    "2017 uppercase",
    "2008 bookstack",
    "2011 a z author ch",
    "2008 reads",
    "2005 reads",
    "2018 tbr",
    "2018 reading l",
    "2016 tbr",
    "2014 fall winter reading",
    "2015 reading challenge book",
    "2017 tbr",
    "2016 2017",
    "2015 to read books",
    "read 2559",
    "gelezen in 2016",
    "read prior to 2007",
    "read before 2007",
    "his",
    "wtf",
    "nope nope nope",
    "kindle own a copy",
    "expedit",
    "chic",
    "to read mm romance",
    "college",
    "f",
    "beach reads",
    "barefoo",
    "customs",
    "in my library",
    "2 star books",
    "library 2017",
    "pinterest recommends",
    "free ebook",
    "to read men in uniform",
    "gilmore",
    "gilmore girls book list",
    "rory gilmore",
    "never again",
    "general non fi",
    "millennium",
    "suspense th",
    "book to movie",
    "romantic",
    "realis",
    "robert langdon",
    "school reading",
    "lit",
    "renaiss",
    "june 2015",
    "new adult romance",
    "harlequin",
    "new series",
    "health and heali",
    "bestsellers",
    "general non fiction",
    "psych",
    "adult",
    "intelligence operative",
    "have audio",
    "waiting i",
    "read for school",
    "swedes and others",
    "carin gerhardsen",
    "your friendly librarian recommends",
    "books read 2017",
    "showb",
    "sparks nicholas",
    "sounds interesting",
    "got",
    "b h",
    "best read",
    "to read giveaways",
    "reordering",
    "entry 2017",
    "estante",
    "head injury",
    "library",
    "space travel",
    "purchased",
    "you",
    "s",
    "pc 200 299",
    "opra",
    "women s prize for fiction",
    "star trek owned",
    "long long ago",
    "series star t",
    "known space",
    "to read horror",
    "history jack whyte",
    "paper ink",
    "7th grade",
    "young",
    "celtic myth",
    "five stars",
    "film related",
    "tra",
    "boston",
    "persons",
    "policier",
    "impo",
    "australian",
    "angel",
    "reads",
    "good just",
    "listening t",
    "homoeopathy",
    "healing",
    "herbs",
    "hea",
    "premier s reading challenge",
    "fa",
    "divergent",
    "divergent series",
    "pub 2012",
    "sounds in",
    "a",
    "zz ab meta none all dates",
    "wdml a",
    "library owned",
    "would read again",
    "klaverblad",
    "did not want to finish",
    "150 200",
    "own the kindle",
    "gu",
    "trying to trade",
    "ars longa vita brevis",
    "looks interesting",
    "bookgroup",
    "wealthy",
    "a kindle cloud",
    "pages",
    "oprah bookclub",
    "gvpl",
    "1 a 2017 reading schedule"]
   