lcgft_mapping = {
        'm m': 'Gay fiction',
        'f f': 'Lesbian fiction',
        'gay': 'Gay fiction',
        'lesbian': 'Lesbian fiction',
        'stories': 'Fiction',
        'tales': 'Fiction',
        'action fiction': 'Action and adventure fiction',
        'adventure fiction': 'Action and adventure fiction',
        'swashbuckler fiction': 'Action and adventure fiction',
        'swashbucklers (fiction)': 'Action and adventure fiction',
        'fantastic fiction': 'Fantasy fiction',
        'heroic fantasy fiction': 'Fantasy fiction',
        'fantasy': 'Fantasy fiction',
        'love stories': 'Romance fiction',
        'romances (love stories)': 'Romance fiction',
        'romantic fiction': 'Romance fiction',
        'romance': 'Romance fiction',
        'occult fiction': 'Paranormal fiction',
        'supernatural fiction': 'Paranormal fiction',
        'supernaturalist fiction': 'Paranormal fiction',
        'paranormal': 'Paranormal fiction',
        'supernatural': 'Paranormal fiction',
        'lycanthropic fiction': 'Werewolf fiction',
        'werwolf fiction': 'Werewolf fiction',
        'werewolves': 'Werewolf fiction',
        'warlock fiction': 'Witch fiction',
        'witchcraft fiction': 'Witch fiction',
        'witchy fiction': 'Witch fiction',
        'witches': 'Witch fiction',
        'warlocks': 'Witch fiction',
        'witchcraft': 'Witch fiction',
        'vampiric fiction': 'Vampire fiction',
        'vampires': 'Vampire fiction',
        'zombies': 'Zombie fiction',
        'ghost fiction': 'Ghost stories',
        'ghost stories': 'Ghost stories',
        'ghosts': 'Ghost stories',
        'monster': 'Monster fiction', # Use with caution - could be about monsters
        'historical romances': 'Historical fiction',
        'regency fiction': 'Historical fiction',
        'romances, historical': 'Historical fiction',
        'historical': 'Historical fiction',
        'anti-war fiction': 'War fiction',
        'antiwar fiction': 'War fiction',
        'combat fiction': 'War fiction',
        'war': 'War fiction',
        'suspense fiction': 'Thrillers (Fiction)',
        'thriller fiction': 'Thrillers (Fiction)',
        'thriller': 'Thrillers (Fiction)',
        'suspense': 'Thrillers (Fiction)',
        'utopian science fiction': 'Utopian fiction',
        'utopic fiction': 'Utopian fiction',
        'utopian': 'Utopian fiction',
        'sci fi': 'Science fiction',
        'sf': 'Science fiction',
        'scifi': 'Science fiction',
        'sci-fi': 'Science fiction',
         "spies": "Spy Fiction",
    "espionage": "Espionage Fiction",
    "histor": "Historical Fiction",
    "science fiction and fantas": "Science Fiction & Fantasy",
        'anti-utopian fiction': 'Dystopian fiction',
        'antiutopian fiction': 'Dystopian fiction',
        'cacotopian fiction': 'Dystopian fiction',
        'counter-utopian fiction': 'Dystopian fiction',
        'counterutopian fiction': 'Dystopian fiction',
        'dystopian science fiction': 'Dystopian fiction',
        'dystopic fiction': 'Dystopian fiction',
        'negative utopian fiction': 'Dystopian fiction',
        'dystopian': 'Dystopian fiction',
        'ya dystopian': 'Dystopian fiction',
        'non fiction' : "Non-Fiction",
        "nonfic": "Non-Fiction",
    "fiction": "Fiction",
    "youth": "Young Adult Fiction",
    "childrens lit": "Children's Literature",
     "paranormal romance": "Paranormal Romance",
    "erotica": "Erotica",
    "sf f": "Science Fiction & Fantasy",
    "classics": "Classic Literature",
    "suspense thriller": "Thriller (Fiction)",
    "japanese": "Japanese Literature",
     "contempor​ary": "Contemporary Fiction", # Spelling variation
    "modern faerie tales": "Fantasy", # Or Fairy Tale Retellings
    "short stories": "Short Stories",
    "faith fict": "Religious Fiction",
        'crime fiction': 'Detective and mystery fiction',
        'detective fiction': 'Detective and mystery fiction',
        'murder mysteries': 'Detective and mystery fiction',
        'mystery fiction': 'Detective and mystery fiction',
        'private eye fiction': 'Detective and mystery fiction',
        'whodunits': 'Detective and mystery fiction',
        'mystery': 'Detective and mystery fiction',
        'thriller mystery': 'Detective and mystery fiction',
        'mystery thriller': 'Detective and mystery fiction',
        'crime': 'Detective and mystery fiction',
        'crime noir fiction': 'Noir fiction',
        'noir': 'Noir fiction',
        'cozies (cozy mysteries)': 'Cozy mysteries',
        'cozy mystery': 'Cozy mysteries',
        'cozy mysteries': 'Cozy mysteries',
        'forensic crime fiction': 'Forensic fiction',
        'forensic detective fiction': 'Forensic fiction',
        'forensics': 'Forensic fiction',
        'city mystery novels': 'City mysteries',
        'city mystery': 'City mysteries',
        'gangsta fiction': 'Urban fiction',
        'gangsta lit': 'Urban fiction',
        'ghetto lit': 'Urban fiction',
        'hip-hop fiction': 'Urban fiction',
        'hip-hop lit': 'Urban fiction',
        'street fiction': 'Urban fiction',
        'street lit': 'Urban fiction',
        'street literature': 'Urban fiction',
        'urban': 'Urban fiction',
        'comedy fiction': 'Humorous fiction',
        'comic fiction': 'Humorous fiction',
        'humor': 'Humorous fiction',
        'comedy': 'Humorous fiction',
        'humour': 'Humorous fiction',
        'satires (fiction)': 'Satirical fiction',
        'satiric fiction': 'Satirical fiction',
        'satirical novels': 'Satirical fiction',
        'satire': 'Satirical fiction',
        'ribald fiction': 'Bawdy fiction',
        'bawdy': 'Bawdy fiction',
        'bragging tales': 'Tall tales',
        'fish stories (tall tales)': 'Tall tales',
        'lying tales': 'Tall tales',
        'stories, tall': 'Tall tales',
        'tales, bragging': 'Tall tales',
        'tales, lying': 'Tall tales',
        'tales, tall': 'Tall tales',
        'tall stories': 'Tall tales',
        'tall talk': 'Tall tales',
        'windies (tales)': 'Tall tales',
        'tall tale': 'Tall tales',
        'tall tales': 'Tall tales',
        'doomsday fiction': 'Apocalyptic fiction',
        'end-of-the-world fiction': 'Apocalyptic fiction',
        'post-apocalyptic fiction': 'Apocalyptic fiction',
        'post-disaster fiction': 'Apocalyptic fiction',
        'post-holocaust fiction': 'Apocalyptic fiction',
        'postapocalyptic fiction': 'Apocalyptic fiction',
        'apocalyptic': 'Apocalyptic fiction',
        'post apocalyptic': 'Apocalyptic fiction',
        'short fiction': 'Short stories',
        'short story': 'Short stories',
        'autobiographies, fictional': 'Fictional autobiographies',
        'memoir-novels': 'Fictional autobiographies',
        'autofiction': 'Autobiographical fiction', # Note the dual mapping
        'young adult': 'Young adult fiction',
        'ya': 'Young adult fiction',
        'young adult fiction': 'Young adult fiction',
        'allohistories (fiction)': 'Alternative histories (Fiction)',
        'alt-history fiction': 'Alternative histories (Fiction)',
        'alternate histories (fiction)': 'Alternative histories (Fiction)',
        'alternate history fiction': 'Alternative histories (Fiction)',
        'alternative history fiction': 'Alternative histories (Fiction)',
        'alternative realities (fiction)': 'Alternative histories (Fiction)',
        'histories, alternative (fiction)': 'Alternative histories (Fiction)',
        'uchronias (fiction)': 'Alternative histories (Fiction)',
        'uchronies (fiction)': 'Alternative histories (Fiction)',
        'what if fiction': 'Alternative histories (Fiction)',
        'what ifs (fiction)': 'Alternative histories (Fiction)',
        'alternative history': 'Alternative histories (Fiction)',
        'biographic fiction': 'Biographical fiction',
        'biographical': 'Biographical fiction',
        'autobiographic fiction': 'Autobiographical fiction',
        'semi-autobiographical fiction': 'Autobiographical fiction',
        'semiautobiographical fiction': 'Autobiographical fiction',
        'autobiographical': 'Autobiographical fiction',
         "comtemporary romance": "Contemporary Romance",
         "contemporary": "Contemporary Fiction",
          "superhero": "Superhero Fiction",
    "paranorm": "Paranormal fiction",
    "kids": "Children's Fiction",
     "historical fiction": "Historical Fiction",
    "les": "LGBTQ+ Fiction", # Or Lesbian Fiction
    "glbtq": "LGBTQ+ Fiction",
        'courtroom fiction': 'Legal fiction (Literature)',
        'law fiction (literature)': 'Legal fiction (Literature)',
        'lawyer fiction': 'Legal fiction (Literature)',
        'trial fiction': 'Legal fiction (Literature)',
        'legal': 'Legal fiction (Literature)',
        'law': 'Legal fiction (Literature)',
        'glbtq+ fiction': 'Queer fiction',
        'lgbt fiction': 'Queer fiction',
        'lgbtq+ fiction': 'Queer fiction',
        'sexual minority fiction': 'Queer fiction',
        'queer': 'Queer fiction',
        'nonfiction novel': 'Nonfiction novels',
        'nonfiction novels': 'Nonfiction novels',
        'nonfiction': 'Creative nonfiction',
        'non-fiction': 'Creative nonfiction',
        'creative non-fiction': 'Creative nonfiction',
        'fourth genre (creative nonfiction)': 'Creative nonfiction',
        'literary nonfiction': 'Creative nonfiction',
        'literary non-fiction': 'Creative nonfiction',
        'narrative nonfiction': 'Creative nonfiction',
        'non-fiction literature': 'Creative nonfiction',
        'non-fiction prose': 'Creative nonfiction',
        'non-fictional literature': 'Creative nonfiction',
        'non-fictional prose': 'Creative nonfiction',
        'nonfiction literature': 'Creative nonfiction',
        'nonfiction prose': 'Creative nonfiction',
        'nonfictional literature': 'Creative nonfiction',
        'nonfictional prose': 'Creative nonfiction',
        'prose literature (creative nonfiction)': 'Creative nonfiction',
        'tales (creative nonfiction)': 'Creative nonfiction',
        'biography': 'Biographies',
        'biography memoirs': 'Biographies',
        'biographies': 'Biographies',
        'bios': 'Biographies',
        'authorized biographies': 'Biographies',
        'biographical notes': 'Biographies',
        'biographical sketches': 'Biographies',
        'histories, life': 'Biographies',
        'life histories': 'Biographies',
        'sketches, biographical': 'Biographies',
        'unauthorized biographies': 'Biographies',
        'magical realist fiction': 'Magic realist fiction',
        'magic realism': 'Magic realist fiction',
        'magical realism': 'Magic realist fiction',
    }